spring:
  application.name: web-ui

  security:
    oauth2:
      client:
        registration:
          webui-client-reg:
            provider: keycloak
            client-id: ${auth.client-id}
            client-secret: ${auth.client-secret}
            authorization-grant-type: authorization_code
            scope:
              - openid
            #redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: ${auth.issuer-uri}
            #authorization-uri: ${auth.openid-uri}/auth
            #token-uri: ${auth.openid-uri}/token
            #jwk-set-uri: ${auth.openid-uri}/certs

auth:
  issuer-uri: ${KEYCLOAK_URI}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  openid-uri: ${auth.issuer-uri}/protocol/openid-connect

client.accounts:
  host: ${ACCOUNTS_HOST}
  port: ${ACCOUNTS_PORT}
