openapi: 3.0.4
info:
  title: Banking - Accounts
  description: This is an accounts service API based on the OpenAPI 3.0 specification.
  version: 1.0.0
components:
  schemas:
    CustomerName:
      type: string
      example: ipet123
    Currency:
      type: string
      enum:
        - "USD"
        - "RUB"
        - "CNY"
        - "EUR"
        - "GBP"
    CurrencyAmount:
      type: number
      example: 1234.56
    Balance:
      type: object
      properties:
        currency:
          $ref: '#/components/schemas/Currency'
        amount:
          $ref: '#/components/schemas/CurrencyAmount'
    AccountNumber:
      type: integer
      format: int64
      example: 438832491231
  parameters:
    AccountNumber:
      name: accountNumber
      description: An account number.
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/AccountNumber'
  responses:
    InvalidRequest:
      description: Invalid request with cause message.
      content:
        text/plain:
          schema:
            type: string
            example: Invalid property format
    AccountOperation:
      description: Amount of money in the account after the operation.
      content:
        application/json:
          schema:
            type: object
            properties:
              currency:
                $ref: '#/components/schemas/Currency'
              totalAmount:
                $ref: '#/components/schemas/CurrencyAmount'

paths:
  /customers:
    post:
      description: Create a new customer.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerName:
                  $ref: '#/components/schemas/CustomerName'
                firstName:
                  type: string
                  example: Ivan
                lastName:
                  type: string
                  example: Petrov
                birthDate:
                  type: string
                  format: date
                  example: 1984-04-17
      responses:
        '200':
          description: Customer created.
        '400':
          $ref: '#/components/responses/InvalidRequest'
  /customers/{customerName}/balance:
    get:
      description: Get the customer balance over all accounts in the specified currency.
      parameters:
        - name: customerName
          description: Customer nickname.
          required: true
          in: path
          schema:
            $ref: '#/components/schemas/CustomerName'
        - name: currency
          description: Currency code for the balance representation.
          required: true
          in: query
          schema:
            $ref: '#/components/schemas/Currency'
      responses:
        '200':
          description: Customer balance.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
        '400':
          $ref: '#/components/responses/InvalidRequest'
  /accounts:
    post:
      description: Create a new customer account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerName:
                  $ref: '#/components/schemas/CustomerName'
                currency:
                  $ref: '#/components/schemas/Currency'
      responses:
        '200':
          description: Created account number.
          content:
            text/plain:
              schema:
                type: object
                properties:
                  number:
                    $ref: '#/components/schemas/AccountNumber'
        '400':
          $ref: '#/components/responses/InvalidRequest'
  /accounts/{accountNumber}:
    get:
      description: Get amount of money in the account.
      parameters:
        - $ref: '#/components/parameters/AccountNumber'
      responses:
        '200':
          description: Amount of money in the account.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
        '400':
          $ref: '#/components/responses/InvalidRequest'
  /accounts/{accountNumber}/top-up:
    put:
      description: Top up the account.
      parameters:
        - $ref: '#/components/parameters/AccountNumber'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                augend:
                  $ref: '#/components/schemas/CurrencyAmount'
      responses:
        '200':
          $ref: '#/components/responses/AccountOperation'
        '400':
          $ref: '#/components/responses/InvalidRequest'
  /accounts/{accountNumber}/withdraw:
    put:
      description: Withdraw money from the account.
      parameters:
        - $ref: '#/components/parameters/AccountNumber'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subtrahend:
                  $ref: '#/components/schemas/CurrencyAmount'
      responses:
        '200':
          $ref: '#/components/responses/AccountOperation'
        '400':
          $ref: '#/components/responses/InvalidRequest'
  /transfer:
    put:
      description: Transfer money from the account to the another account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                senderAccountNumber:
                  $ref: '#/components/schemas/AccountNumber'
                receiverAccountNumber:
                  $ref: '#/components/schemas/AccountNumber'
                senderCurrencyAmount:
                  $ref: '#/components/schemas/CurrencyAmount'
      responses:
        '200':
          description: Successful transfer.
          content:
            text/plain:
              schema:
                type: object
                properties:
                  senderCurrency:
                    $ref: '#/components/schemas/Currency'
                  totalSenderAmount:
                    $ref: '#/components/schemas/CurrencyAmount'
        '400':
          $ref: '#/components/responses/InvalidRequest'
