spring:
  application.name: converter

  http.client:
    connect-timeout: 3s
    read-timeout: 2s

client.rates:
  host: ${RATES_HOST}
  port: ${RATES_PORT}

grpc.client.rates:
  address: ${client.rates.host}:${client.rates.port}
  enable-keep-alive: true
  keep-alive-without-calls: true
  negotiation-type: PLAINTEXT
