spring:
  application.name: converter

  http.client:
    connect-timeout: 3s
    read-timeout: 2s

  grpc.client.channels:
    rates:
      address: ${client.rates.host}:${client.rates.port}
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: PLAINTEXT

  security:
    oauth2:
      resourceserver:
        jwt.jwk-set-uri: ${auth.server-uri}/realms/${auth.realm}/protocol/openid-connect/certs
      client:
        registration:
          converter-client-reg:
            provider: keycloak
            client-id: ${auth.client-id}
            client-secret: ${auth.client-secret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: ${auth.server-uri}/realms/${auth.realm}/protocol/openid-connect/token

auth:
  server-uri: ${KEYCLOAK_URI}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

client.rates:
  host: ${RATES_HOST}
  port: ${RATES_PORT}
